xcodeproj 'XNGAPIClientTesterExample'
workspace '../XNGAPIClientTesterExample'

platform :ios, '7.0'

pod 'XNGAPIClientTester', :path => '../XNGAPIClientTester.podspec'

target :XNGAPIClientTesterExampleTests, :exclusive => true do
  pod 'Expecta'
  pod 'OCMock'
end
